### ISSUE TITLE
Is out_ptr limited to unique_ptr types?

### ISSUE THREAD

**Issue by KingDuckZ** [ThePhD/out_ptr#1]
I'm a bit confused because out_ptr() seems to accept anything and uses type traits to deduce the pointer type inside the smart pointer, but then clever_out_ptr_impl.hpp hardcodes unique_ptr inside the can_aliasing_optimization helper.

In fact I'm calling out_ptr with a shared_ptr and my code is crashing as the double pointer returned by the resulting out_ptr object is wrong.

**Comment by ThePhD** [comment]
Show me the code that crashes. We have tests for unique and shared. I need a minimal repro.

**Comment by ThePhD** [comment]
@KingDuckZ `inout_ptr` cannot work with reallocating functions. I should probably add a hard error to make people not do that.

`inout_ptr` only works when there is a way to take ownership away from the smart pointer you pass in. This is because we need to ensure that the smart pointer does not delete the handle, because the C-style function (in this case, avformat_open_input) is _already_ going to delete the pointer.

`std::shared_ptr` does not make sense here. You can't share ownership when there is clearly 1 owner, and that 1 owner is responsible for potential reallocation (as `avformat_open_input` dictates in its documentation). It double-deletes because some shared pointer -- upon being the last one -- dies and deletes the already-deleted value.

I will work on editing the library so you get a compile-time error explaining this. But, you should look into rearchitecting your code a little bit: std::shared_ptr is not a good fit for reallocating functions.

**Comment by ThePhD** [comment]
I updated the paper going to the San Diego C++ Meeting Mailing, and I added a static_assert in the code to make sure this doesn't trip you up again.

Thanks for reporting this.

**Comment by KingDuckZ** [comment]
ThePhD thanks for the detailed explanation, it makes lots of sense indeed.
You're right that code shouldn't be using shared_ptr, I was trying to make it work with as little change as possible but after that and other more recent problems I'm finding a huge refactoring less and less avoidable. I'll make sure to turn everything into unique_ptr (there is no shared ownership anyways). Your out_ptr will still be massively helpful.
